server:
  host: "0.0.0.0"
  port: "8080"

database:
  driver: "postgres"
  dsn: "user=user password=password dbname=antibruteforce host=db port=5432 sslmode=disable"

redis:
  address: "redis:6379"

logger:
  level: "debug"

rate_limiter:
  login_limit: 10
  password_limit: 100
  ip_limit: 1000